SET NOCOUNT ON
GO

USE [master]
GO
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME=N'2DOK_MAG')
		DROP DATABASE [2DOK_MAG]
GO

DECLARE @device_directory NVARCHAR(520)
SELECT @device_directory = SUBSTRING(FILENAME, 1, CHARINDEX(N'MASTER.MDF', LOWER(FILENAME)) - 1)
FROM MASTER.DBO.SYSALTFILES WHERE DBID = 1 AND FILEID = 1

DECLARE @execute_command NVARCHAR(520)
SET @execute_command = N'CREATE DATABASE [2DOK_MAG] ' + 
      'ON PRIMARY (NAME = N''2DOK_MAG'', FILENAME = N''' + @device_directory + N'2DOK_MAG.MDF'', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB) ' +
      'LOG ON (NAME = N''2DOK_MAG_LOG'', FILENAME = N''' + @device_directory + N'2DOK_MAG.LDF'', SIZE = 8192KB , MAXSIZE = 2048GB, FILEGROWTH = 65536KB) ' +
      'WITH CATALOG_COLLATION = DATABASE_DEFAULT'

EXECUTE (@execute_command)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
    DECLARE @execute_command NVARCHAR(520)
    SET @execute_command = N'EXEC [2DOK_MAG].[dbo].[sp_fulltext_database] @action = ''enable'''
	EXECUTE (@execute_command)
end
GO

ALTER DATABASE [2DOK_MAG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [2DOK_MAG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [2DOK_MAG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [2DOK_MAG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [2DOK_MAG] SET ARITHABORT OFF 
GO

ALTER DATABASE [2DOK_MAG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [2DOK_MAG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [2DOK_MAG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [2DOK_MAG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [2DOK_MAG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [2DOK_MAG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [2DOK_MAG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [2DOK_MAG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [2DOK_MAG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [2DOK_MAG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [2DOK_MAG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [2DOK_MAG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [2DOK_MAG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [2DOK_MAG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [2DOK_MAG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [2DOK_MAG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [2DOK_MAG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [2DOK_MAG] SET RECOVERY FULL 
GO

ALTER DATABASE [2DOK_MAG] SET  MULTI_USER 
GO

ALTER DATABASE [2DOK_MAG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [2DOK_MAG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [2DOK_MAG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [2DOK_MAG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [2DOK_MAG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [2DOK_MAG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [2DOK_MAG] SET QUERY_STORE = OFF
GO

ALTER DATABASE [2DOK_MAG] SET  READ_WRITE 
GO

USE [2DOK_MAG]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DOKMAG](
	[ID_DOKMAG] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [datetime] NOT NULL,
	[NUMER_KLIENTA] [varchar](50) NOT NULL,
	[NAZWA] [varchar](50) NULL,
	[NETTO] [decimal](12, 2) NOT NULL,
	[BRUTTO] [decimal](12, 2) NOT NULL,
 CONSTRAINT [PK_DOKMAG] PRIMARY KEY CLUSTERED 
(
	[ID_DOKMAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOKMAG_ASORT](
	[ID_DOKMAG] [int] NOT NULL,
	[ID_DOKMAG_ASORT] [int] IDENTITY(1,1) NOT NULL,
	[NAZWA] [varchar](80) NULL,
	[ILOSC] [decimal](12, 4) NOT NULL,
	[NETTO] [decimal](12, 2) NOT NULL,
	[BRUTTO] [decimal](12, 2) NOT NULL,
 CONSTRAINT [PK_DOKMAG_ASORT] PRIMARY KEY CLUSTERED 
(
	[ID_DOKMAG] ASC,
	[ID_DOKMAG_ASORT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DOKMAG_ASORT]  WITH NOCHECK ADD  CONSTRAINT [FK_DOKMAG_ASORT_DOKMAG] FOREIGN KEY([ID_DOKMAG])
REFERENCES [dbo].[DOKMAG] ([ID_DOKMAG])
GO

ALTER TABLE [dbo].[DOKMAG_ASORT] CHECK CONSTRAINT [FK_DOKMAG_ASORT_DOKMAG]
GO
